print("Enter elements of list1")
list1 = list(map(int, input().split()))
print("Enter elements of list2")
list2 = list(map(int, input().split()))
s1 = set(list1)
s2 = set(list2)
s = s1.intersection(s2)
print("Intersection of lists")
print(list(s))
